### ISSUE TITLE
Add gRPC support

### ISSUE THREAD

**Issue by swilgosz** [yousty/event_store_client#31]
### Overview

Add a [gRPC](https://grpc.io/docs/what-is-grpc/introduction/) adapter for newer versions of EventStoreDB.

### Todo:

- [x] Reading events from stream
- [x] Reading all events (paginating through all)
- [x] Publishing events
- [x] Subscribing to stream (persistent subscriptions)
- [x] Consuming feeds
- [x] Subscriptions management
- [x] Projections management
- [x] Joining streams (projections)
- [x] Authentication mechanism

**Comment by swilgosz** [comment]
Resolved with 1.0
